name: 'Dependency Review'
on: 
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v1
        with:
          egress-policy: block
          disable-telemetry: true
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - name: 'Checkout Repository'
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@1360a344ccb0ab6e9475edef90ad2f46bf8003b1
